MODEL:
#  TYPE: ResNet101
#  TYPE: ResNet18
  TYPE: VNET
  NUM_CLASSES: 2

DATA:
  DATASET: 'CP'
  DATA_PATH: '../data'
  BATCH_SIZE: 1
  NUM_WORKERS: 4
  IMG_SIZE: [64, 256, 256]  #对应
TEST:
  SHUFFLE: False
#  MODEL_PATH: '/media/data1/jiachuang/projects/301kidney_classification/train/saved_models/ResNet18_checkpoints/CP_seg_classify_CP_03_01_14_04/CP_seg_classify_best.pth.tar' #
#  MODEL_PATH: '/media/data1/jiachuang/projects/301kidney_classification/train/saved_models/ResNet18_checkpoints/CP_seg_classify_CP_03_01_14_04/CP_seg_classify_last.pth.tar' #0.66
  # MODEL_PATH: '/media/data1/jiachuang/projects/301kidney_classification/train/saved_models/ResNet10_checkpoints/CP_seg_classify_CP_03_03_04_34/CP_seg_classify_best.pth.tar'
  # MODEL_PATH: '/home7/yilizhati/projects/301kidney_classification/train/saved_models/ResNet10_checkpoints/CP_seg_classify_CP_06_25_01_13/CP_classify_best.pth.tar'
  # MODEL_PATH: '/home7/yilizhati/projects/301kidney_classification/train/saved_models/ResNet10_checkpoints/CP_seg_classify_CP_06_28_07_48/CP_classify_best.pth.tar'
  MODEL_PATH: '/home7/yilizhati/projects/301kidney_seg_classify/train/saved_models/VNET_checkpoints/CP_seg_classify_CP_08_08_15_48/CP_segment_best.pth.tar'

TAG: CP_inference