MODEL:
#  TYPE: ResNet101
#  TYPE: ResNet18
  TYPE: VNET
  NUM_CLASSES: 2

DATA:
  DATASET: 'EP'
  DATA_PATH: '../data'
  BATCH_SIZE: 1
  NUM_WORKERS: 4
  IMG_SIZE: [64, 256, 256]  #对应
TEST:
  SHUFFLE: False
#  MODEL_PATH: '/media/data1/jiachuang/projects/301kidney_classification/train/saved_models/ResNet18_checkpoints/EP_seg_classify_EP_03_01_14_04/EP_seg_classify_best.pth.tar' #
#  MODEL_PATH: '/media/data1/jiachuang/projects/301kidney_classification/train/saved_models/ResNet18_checkpoints/EP_seg_classify_EP_03_01_14_04/EP_seg_classify_last.pth.tar' #0.66
  # MODEL_PATH: '/media/data1/jiachuang/projects/301kidney_classification/train/saved_models/ResNet10_checkpoints/EP_seg_classify_EP_03_03_04_34/EP_seg_classify_best.pth.tar'
  # MODEL_PATH: '/home7/yilizhati/projects/301kidney_seg_extract/train/saved_models/VNET_checkpoints/EP_seg_classify_EP_07_29_16_38/EP_segment_best.pth.tar' #0.71
  # MODEL_PATH: '/home7/yilizhati/projects/301kidney_seg_extract/train/saved_models/VNET_checkpoints/EP_seg_classify_EP_07_28_17_35/EP_classify_best.pth.tar'  #cosine调度器+早停0.76  0.73
  MODEL_PATH: '/home7/yilizhati/projects/301kidney_seg_classify/train/saved_models/VNET_checkpoints/EP_seg_classify_EP_08_04_08_17/EP_segment_last.pth.tar' #0.72
TAG: EP_inference