MODEL:
#  TYPE: ResNet101
#  TYPE: ResNet18
  TYPE: VNET
  NUM_CLASSES: 2

DATA:
  DATASET: 'NP'
  DATA_PATH: '../data'
  BATCH_SIZE: 1
  NUM_WORKERS: 4
  IMG_SIZE: [64, 256, 256]  #对应
TEST:
  SHUFFLE: False
#  MODEL_PATH: '/media/data1/jiachuang/projects/301kidney_classification/train/saved_models/ResNet18_checkpoints/NP_seg_classify_NP_03_01_14_04/NP_seg_classify_best.pth.tar' #
#  MODEL_PATH: '/media/data1/jiachuang/projects/301kidney_classification/train/saved_models/ResNet18_checkpoints/NP_seg_classify_NP_03_01_14_04/NP_seg_classify_last.pth.tar' #0.66
  MODEL_PATH: '/home7/yilizhati/projects/301kidney_seg_classify/train/saved_models/VNET_checkpoints/NP_seg_classify_NP_08_08_01_17/NP_segment_best.pth.tar'
TAG: NP_inference