MODEL:
#  TYPE: ResNet101
#  TYPE: ResNet18
  TYPE: VNET
  NUM_CLASSES: 2

DATA:
  DATASET: 'T1WI'
  DATA_PATH: '../data'
  BATCH_SIZE: 1
  NUM_WORKERS: 4
  IMG_SIZE: [64, 256, 256]  #对应
TEST:
  SHUFFLE: False
#  MODEL_PATH: '/media/data1/jiachuang/projects/301kidney_classification/train/saved_models/ResNet18_checkpoints/T1WI_seg_classify_T1WI_03_01_14_04/T1WI_seg_classify_best.pth.tar' #
#  MODEL_PATH: '/media/data1/jiachuang/projects/301kidney_classification/train/saved_models/ResNet18_checkpoints/T1WI_seg_classify_T1WI_03_01_14_04/T1WI_seg_classify_last.pth.tar' #0.66
  MODEL_PATH: '/home7/yilizhati/projects/301kidney_seg_classify/train/saved_models/VNET_checkpoints/T1WI_seg_classify_T1WI_08_11_11_30/T1WI_segment_last.pth.tar'
TAG: T1WI_inference